"""BlenderCodeSandbox — whitelist-based code validator for Blender exec() calls.

Strategy:
- BLOCK known dangerous modules: os, sys, subprocess, socket, shutil, importlib
- BLOCK file write patterns: open(..., 'w'), open(..., 'a')
- BLOCK network patterns: urllib, requests, httpx, socket
- ALLOW all bpy.* calls freely
- ALLOW read-only file operations (open(..., 'r') for asset loading)
- Unknown patterns: WARN in log but allow (forward compatibility with new bpy APIs)

Design: data-driven — BLOCKED_PATTERNS list, easy to extend without code changes.
"""

from __future__ import annotations

import logging
import re

from src.core.ports.code_sandbox_port import CodeSandboxPort, SandboxResult

logger = logging.getLogger(__name__)

# Each entry: (regex_pattern, human_readable_reason)
_BLOCKED_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"\bimport\s+os\b"), "import os — filesystem/process access"),
    (re.compile(r"\bimport\s+sys\b"), "import sys — interpreter manipulation"),
    (re.compile(r"\bimport\s+subprocess\b"), "import subprocess — shell execution"),
    (re.compile(r"\bfrom\s+os\b"), "from os — filesystem/process access"),
    (re.compile(r"\bfrom\s+subprocess\b"), "from subprocess — shell execution"),
    (re.compile(r"\b__import__\s*\("), "__import__() — dynamic import bypass"),
    (re.compile(r"\bimportlib\b"), "importlib — dynamic import"),
    (re.compile(r"\bexec\s*\("), "nested exec() — code injection"),
    (re.compile(r"\beval\s*\("), "eval() — arbitrary expression evaluation"),
    (re.compile(r"\bopen\s*\([^)]*['\"][wa]['\"]"), "open(..., 'w'/'a') — file write"),
    (re.compile(r"\burllib\b"), "urllib — outbound network"),
    (re.compile(r"\brequests\b"), "requests — outbound network"),
    (re.compile(r"\bhttpx\b"), "httpx — outbound network"),
    (re.compile(r"\bsocket\s*\.\s*socket\b"), "socket.socket() — raw network"),
    (re.compile(r"\bshutil\b"), "shutil — filesystem manipulation"),
    (re.compile(r"\bpickle\b"), "pickle — arbitrary deserialization"),
    (re.compile(r"\bctypes\b"), "ctypes — native code execution"),
    (re.compile(r"\b__builtins__\b"), "__builtins__ manipulation"),
    (re.compile(r"\bgetattr\s*\(\s*__"), "getattr on dunder — attribute bypass"),
]


class BlenderCodeSandbox(CodeSandboxPort):
    """Whitelist-based sandbox for Blender Python code generated by LLMs."""

    def validate(self, code: str) -> SandboxResult:
        violations: list[str] = []
        for pattern, reason in _BLOCKED_PATTERNS:
            if pattern.search(code):
                violations.append(reason)
                logger.warning("Code sandbox blocked pattern: %s", reason)

        if violations:
            logger.warning(
                "Code sandbox rejected code (%d violation(s)): %s",
                len(violations),
                "; ".join(violations),
            )

        return SandboxResult(
            allowed=not bool(violations),
            violations=tuple(violations),
        )
